![Header](images/01/packt publishing.jpg)

# Getting Started with Raw Data

In the world of data science, raw data comes in many forms and sizes. There is a
lot of information that can be extracted from this raw data. To give an example,
Amazon collects click stream data that records each and every click of the user on the
website. This data can be utilized to understand if a user is a price-sensitive customer
or prefer more popularly rated products. You must have noticed recommended
products in Amazon; they are derived using such data.
The first step towards such an analysis would be to parse raw data. The parsing of
the data involves the following steps:
* Extracting data from the source: Data can come in many forms, such as Excel, CSV, JSON, databases, and so on. Python makes it very easy to read data from these sources with the help of some useful packages, which will be covered in this chapter.
* Cleaning the data: Once a sanity check has been done, one needs to clean the data appropriately so that it can be utilized for analysis. You may have a dataset about students of a class and details about their height, weight, and marks. There may also be certain rows with the height or weight missing. Depending on the analysis being performed, these rows with missing values can either be ignored or replaced with the average height or weight.

In this chapter we will cover the following topics:

* Exploring arrays with NumPy
* Handling data with pandas
* Reading and writing data from various formats
* Handling missing data
* Manipulating data

### The world of arrays with NumPy
Python, by default, comes with a data structure, such as List, which can be utilized
for array operations, but a Python list on its own is not suitable to perform heavy
mathematical operations, as it is not optimized for it.
NumPy is a wonderful Python package produced by Travis Oliphant, which
has been created fundamentally for scientific computing. It helps handle large
multidimensional arrays and matrices, along with a large library of high-level
mathematical functions to operate on these arrays.
A NumPy array would require much less memory to store the same amount of data
compared to a Python list, which helps in reading and writing from the array in a
faster manner.

### Creating an array
A list of numbers can be passed to the following array function to create a NumPy
array object:

In [5]:
import numpy as np
n_array = np.array([[0, 1, 2, 3],
[4, 5, 6, 7],
[8, 9, 10, 11]])

n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

A NumPy array object has a number of attributes, which help in giving information
about the array. Here are its important attributes:

**ndim:** This gives the number of dimensions of the array. The following shows
that the array that we defined had two dimensions:

In [6]:
n_array.ndim

2

n_array has a rank of 2, which is a 2D array.
**shape:** This gives the size of each dimension of the array:

In [7]:
n_array.shape

(3, 4)

The first dimension of n_array has a size of 3 and the second dimension has
a size of 4. This can be also visualized as three rows and four columns.
**size:** This gives the number of elements:

In [8]:
n_array.size

12

The total number of elements in n_array is 12.
**dtype:** This gives the datatype of the elements in the array:

In [9]:
n_array.dtype.name

'int32'

The number is stored as int64 in n_array.

### Mathematical operations
When you have an array of data, you would like to perform certain mathematical
operations on it. We will now discuss a few of the important ones in the following
sections.

### Array subtraction
The following commands subtract the a array from the b array to get the resultant
c array. The subtraction happens element by element:

In [10]:
a = np.array( [11, 12, 13, 14])
b = np.array( [ 1, 2, 3, 4])
c = a - b
c

array([10, 10, 10, 10])

Do note that when you subtract two arrays, they should be of equal dimensions

### Squaring an array
The following command raises each element to the power of 2 to obtain this result:

In [11]:
b**2

array([ 1,  4,  9, 16])

### A trigonometric function performed on the array
The following command applies cosine to each of the values in the b array to obtain
the following result:

In [12]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Conditional operations
The following command will apply a conditional operation to each of the elements of
the b array, in order to generate the respective Boolean values:

In [13]:
b<2

array([ True, False, False, False], dtype=bool)

### Matrix multiplication
Two matrices can be multiplied element by element or in a dot product. The
following commands will perform the element-by-element multiplication:

In [17]:
A1 = np.array([[1, 1],
[0, 1]])
A1

array([[1, 1],
       [0, 1]])

In [18]:
A2 = np.array([[2, 0],
[3, 4]])
A2

array([[2, 0],
       [3, 4]])

In [19]:
A1 * A2

array([[2, 0],
       [0, 4]])

In [20]:
np.dot(A1, A2)

array([[5, 4],
       [3, 4]])

### Indexing and slicing
If you want to select a particular element of an array, it can be achieved using indexes:

In [ ]:
n_array[0,1]

The preceding command will select the first array and then select the second value in
the array. It can also be seen as an intersection of the first row and the second column
of the matrix.
If a range of values has to be selected on a row, then we can use the following
command:

In [22]:
n_array[ 0 , 0:3 ]

array([0, 1, 2])

The 0:3 value selects the first three values of the first row.
The whole row of values can be selected with the following command:

In [23]:
n_array[ 0 , : ]

array([0, 1, 2, 3])

Using the following command, an entire column of values need to be selected:

In [24]:
n_array[ : , 1 ]

array([1, 5, 9])

### Shape manipulation
Once the array has been created, we can change the shape of it too. The following
command flattens the array:

In [25]:
n_array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

The following command reshapes the array in to a six rows and two columns format.
Also, note that when reshaping, the new shape should have the same number of
elements as the previous one:

In [30]:
n_array.shape = (6,2)
n_array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

The array can be transposed too:

In [31]:
n_array.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

### Empowering data analysis with pandas
The pandas library was developed by Wes McKinny when he was working at
AQR Capital Management. He wanted a tool that was flexible enough to perform
quantitative analysis on financial data. Later, Chang She joined him and helped
develop the package further.
The pandas library is an open source Python library, specially designed for data
analysis. It has been built on NumPy and makes it easy to handle data. NumPy is a
fairly low-level tool that handles matrices really well.
The pandas library brings the richness of R in the world of Python to handle data. It's
has efficient data structures to process data, perform fast joins, and read data from
various sources, to name a few.

The data structure of pandas
The pandas library essentially has three data structures:
1. Series
2. DataFrame
3. Panel
Series
Series is a one-dimensional array, which can hold any type of data, such as integers,
floats, strings, and Python objects too. A series can be created by calling the following:


In [5]:
import pandas as pd
pd.Series(np.random.randn(5))

NameError: name 'np' is not defined

The random.randn parameter is part of the NumPy package and it generates random
numbers. The series function creates a pandas series that consists of an index, which
is the first column, and the second column consists of random values. At the bottom
of the output is the datatype of the series.
The index of the series can be customized by calling the following:

In [ ]:
pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

A series can be derived from a Python dict too:

In [ ]:
d = {'A': 10, 'B': 20, 'C': 30}
pd.Series(d)

### DataFrame
DataFrame is a 2D data structure with columns that can be of different datatypes. It
can be seen as a table. A DataFrame can be formed from the following data structures:
* A NumPy array
* Lists
* Dicts
* Series
* A 2D NumPy array

A DataFrame can be created from a dict of series by calling the following commands:

In [ ]:
d = {'c1': pd.Series(['A', 'B', 'C']),
'c2': pd.Series([1, 2., 3., 4.])}
df = pd.DataFrame(d)
df

In [ ]:
The DataFrame can be created using a dict of lists too:

In [6]:
d= {'c1': ['A', 'B', 'C', 'D'],'c2': [1, 2.0, 3.0, 4.0]}
df = pd.DataFrame(d)
print df

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-6-ee89cc02fcd2>, line 3)

### Panel
A Panel is a data structure that handles 3D data. The following command is an
example of panel data:

In [2]:
d = {'Item1': pd.DataFrame(np.random.randn(4, 3)),
'Item2': pd.DataFrame(np.random.randn(4, 2))}
pd.Panel(d)

NameError: name 'pd' is not defined

The preceding command shows that there are 2 DataFrames represented by two
items. There are four rows represented by four major axes and three columns
represented by three minor axes.

### Inserting and exporting data
The data is stored in various forms, such as CSV, TSV, databases, and so on. The
pandas library makes it convenient to read data from these formats or to export to
these formats. We'll use a dataset that contains the weight statistics of the school
students from the U.S..
We'll be using a file with the following structure:

![Table](images/01/table.JPG)

### CSV
To read data from a .csv file, the following read_csv function can be used:

In [7]:
d = pd.read_csv('Data/Student_Weight_Status_Category_
Reporting_Results__Beginning_2010.csv')
d[0:5]['AREA NAME']

SyntaxError: EOL while scanning string literal (<ipython-input-7-2e0118a82768>, line 1)

The read_csv function takes the path of the .csv file to input the data. The
command after this prints the first five rows of the Location column in the data.
To write a data to the .csv file, the following to_csv function can be used:

In [ ]:
d = {'c1': pd.Series(['A', 'B', 'C']),
'c2': pd.Series([1, 2., 3., 4.])}
df = pd.DataFrame(d)
df.to_csv('sample_data.csv')

The DataFrame is written to a .csv file by using the to_csv method. The path and
the filename where the file needs to be created should be mentioned.

### XLS
In addition to the pandas package, the xlrd package needs to be installed for pandas
to read the data from an Excel file:

In [ ]:
d=pd.read_excel('Data/Student_Weight_Status_Category
_Reporting_Results__Beginning_2010.xls')

The preceding function is similar to the CSV reading command. To write to an Excel
file, the xlwt package needs to be installed:

In [ ]:
df.to_excel('sample_data.xls')

### JSON
To read the data from a JSON file, Python's standard json package can be used. The
following commands help in reading the file:

In [ ]:
import json
json_data = open('Data/Student_Weight_Status_Category
_Reporting_Results__Beginning_2010.json')
data = json.load(json_data)
json_data.close()

In the preceding command, the open() function opens a connection to the file. The
json.load() function loads the data into Python. The json_data.close() function
closes the connection to the file.
The pandas library also provides a function to read the JSON file, which can be
accessed using pd.read_json().

### Database
To read data from a database, the following function can be used:

In [ ]:
pd.read_sql_table(table_name, con)

The preceding command generates a DataFrame. If a table name and an SQLAlchemy
engine are given, they return a DataFrame. This function does not support the DBAPI
connection. The following are the description of the parameters used:
* table_name: This refers to the name of the SQL table in a database
* con: This refers to the SQLAlchemy engine
The following command reads SQL query into a DataFrame:

In [ ]:
pd.read_sql_query(sql, con)

The following are the description of the parameters used:
• sql: This refers to the SQL query that is to be executed
• con: This refers to the SQLAlchemy engine
    
### Data cleansing
The data in its raw form generally requires some cleaning so that it can be analyzed
or a dashboard can be created on it. There are many reasons that data might
have issues. For example, the Point of Sale system at a retail shop might have
malfunctioned and inputted some data with missing values. We'll be learning
how to handle such data in the following section.  

### Checking the missing data
Generally, most data will have some missing values. There could be various reasons
for this: the source system which collects the data might not have collected the values
or the values may never have existed. Once you have the data loaded, it is essential
to check the missing elements in the data. Depending on the requirements, the
missing data needs to be handled. It can be handled by removing a row or replacing
a missing value with an alternative value.
In the Student Weight data, to check if the location column has missing value,
the following command can be utilized:


In [ ]:
d['Location 1'].isnull()

The notnull() method will output each row of the value as TRUE or FALSE. If it's
False, then there is a missing value. This data can be aggregated to find the number
of instances of the missing value:

In [ ]:
d['Location 1'].isnull().value_counts()

The preceding command shows that the Location 1 column has 24 instances of
missing values. These missing values can be handled by either removing the rows
with the missing values or replacing it with some values. To remove the rows,
execute the following command:

In [ ]:
d = d['Location 1'].dropna()

To remove all the rows with an instance of missing values, use the following command:

In [ ]:
d = d.dropna(how='any')

### Filling the missing data
Let's define some DataFrames to work with:

In [ ]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a0', 'a10',
'a20', 'a30', 'a40'],
columns=['X', 'Y', 'Z'])

In [ ]:
df

We'll now add some extra row indexes, which will create null values in our DataFrame:

In [ ]:
df2 = df2.reindex(['a0', 'a1', 'a10', 'a11', 'a20', 'a21',
'a30', 'a31', 'a40', 'a41'])

In [ ]:
df2

If you want to replace the null values in the df2 DataFrame with a value of zero in
the following case, execute the following command:

In [ ]:
df2.fillna(0)

If you want to fill the value with forward propagation, which means that the
value previous to the null value in the column will be used to fill the null value,
the following command can be used:

In [ ]:
df2.fillna(method='pad') #filling with forward propagation

If you want to fill the null values of the column with the column mean, then the
following command can be utilized:

In [ ]:
df2.fillna(df2.mean())

### String operations
Sometimes, you would want to modify the string field column in your data.
The following technique explains some of the string operations:
• Substring: Let's start by choosing the first five rows of the AREA NAME
column in the data as our sample data to modify:

In [ ]:
df = pd.read_csv('Data/Student_Weight_Status_Category_
Reporting_Results__Beginning_2010.csv')
df['AREA NAME'][0:5]

In order to extract the first word from the Area Name column, we'll use the
extract function as shown in the following command:

In [ ]:
df['AREA NAME'][0:5].str.extract('(\w+)')

In the preceding command, the str attribute of the series is utilized. The str
class contains an extract method, where a regular expression could be fed
to extract data, which is very powerful. It is also possible to extract a second
word in AREA NAME as a separate column:

In [ ]:
df['AREA NAME'][0:5].str.extract('(\w+)\s(\w+)')

To extract data in different columns, the respective regular expression needs
to be enclosed in separate parentheses.
* Filtering: If we want to filter rows with data on ELEMENTARY school, then the following command can be used:

In [ ]:
df[df['GRADE LEVEL'] == 'ELEMENTARY']

* Uppercase: To convert the area name to uppercase, we'll use the following command:

In [ ]:
df['AREA NAME'][0:5].str.upper()

Since the data strings are in uppercase already, there won't be any
difference seen.

* Lowercase: To convert Area Name to lowercase, we'll use the following command:

In [ ]:
df['AREA NAME'][0:5].str.lower()

* Length: To find the length of each element of the Area Name column, we'll use the following command:

In [ ]:
df['AREA NAME'][0:5].str.len()

* Split: To split Area Name based on a whitespace, we'll use the following command:

In [ ]:
df['AREA NAME'][0:5].str.split(' ')

* Replace: If we want to replace all the area names ending with DISTRICT to DIST, then the following command can be used:

In [ ]:
df['AREA NAME'][0:5].str.replace('DISTRICT$', 'DIST')

The first argument in the replace method is the regular expression used to
identify the portion of the string to replace. The second argument is the value
for it to be replaced with.

### Merging data
To combine datasets together, the concat function of pandas can be utilized.
Let's take the Area Name and the County columns with its first five rows:

In [ ]:
d[['AREA NAME', 'COUNTY']][0:5]

We can divide the data as follows:

In [ ]:
p1 = d[['AREA NAME', 'COUNTY']][0:2]
p2 = d[['AREA NAME', 'COUNTY']][2:5]

The first two rows of the data are in p1 and the last three rows are in p2. These pieces
can be combined using the concat() function:

In [ ]:
pd.concat([p1,p2])

The combined pieces can be identified by assigning a key:

In [ ]:
concatenated = pd.concat([p1,p2], keys = ['p1','p2'])
concatenated

Using the keys, the pieces can be extracted back from the concatenated data:

In [ ]:
concatenated.ix['p1']

### Data operations
Once the missing data is handled, various operations can be performed on the data.

### Aggregation operations
There are a number of aggregation operations, such as average, sum, and so on,
which you would like to perform on a numerical field. These are the methods
used to perform it:

In [ ]:
data = d[d['GRADE LEVEL'] == 'ELEMENTARY']

Now, we'll find the mean using the following command:

In [ ]:
data['NO. OBESE'].mean()

The elementary grade level data is filtered and stored in the data object. The
NO. OBESE column is selected, which contains the number of obese students
and using the mean() method, the average is taken out.

**SUM:** To find out the total number of elementary students who are obese
across all the school, use the following command:

In [ ]:
data['NO. OBESE'].sum()

**MAX:** To get the maximum number of students that are obese in an
elementary school, use the following command:

In [ ]:
data['NO. OBESE'].max()

**MIN:** To get the minimum number of students that are obese in an
elementary school, use the following command:

In [ ]:
data['NO. OBESE'].min()

**STD:** To get the standard deviation of the number of obese students, use the
following command:

In [ ]:
data['NO. OBESE'].std()

**COUNT:** To count the total number of schools with the ELEMENTARY grade in
the DELAWARE county, use the following command:

In [ ]:
data = df[(d['GRADE LEVEL'] == 'ELEMENTARY') &
(d['COUNTY'] == 'DELAWARE')]
data['COUNTY'].count()

The table is filtered for the ELEMENTARY grade and the DELAWARE county.
Notice that the conditions are enclosed in parentheses. This is to ensure that
individual conditions are evaluated and if the parentheses are not provided,
then Python will throw an error.

### Joins
SQL-like joins can be performed on the DataFrame using pandas. Let's define
a lookup DataFrame, which assigns levels to each of the grades using the
following command:

In [ ]:
grade_lookup = {'GRADE LEVEL': pd.Series(['ELEMENTARY',
'MIDDLE/HIGH', 'MISC']),
'LEVEL': pd.Series([1, 2, 3])}

In [ ]:
grade_lookup = DataFrame(grade_lookup)

Let's take the first five rows of the GRADE data column as an example for performing
the joins:

In [ ]:
df[['GRADE LEVEL']][0:5]

### The inner join
The following image is a sample of an inner join:

![Set 1](images/01/set_1.JPG)

An inner join can be performed with the following command:

In [ ]:
d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']),
on=['GRADE LEVEL'], how='inner')
d_sub[['GRADE LEVEL', 'LEVEL']]

The join takes place with the join() method. The first argument takes the
DataFrame on which the lookup takes place. Note that the grade_lookup
DataFrame's index is being set by the set_index() method. This is essential
for a join, as without it, the join method won't know on which column to join
the DataFrame to.
The second argument takes a column of the d DataFrame to join the data. The third
argument defines the join as an inner join.

### The left outer join
The following image is a sample of a left outer join:

![Set 2](images/01/set_2.JPG)

A left outer join can be performed with the following commands:

In [ ]:
d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']),
on=['GRADE LEVEL'], how='left')
d_sub[['GRADE LEVEL', 'LEVEL']]

You can notice that **DISTRICT TOTAL** has missing values for a level column, as the
grade_lookup DataFrame does not have an instance for **DISTRICT TOTAL**.

### The full outer join
The following image is a sample of a full outer join:

![Set 3](images/01/set_3.JPG)

The full outer join can be performed with the following commands:

In [ ]:
d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']),
on=['GRADE LEVEL'], how='outer')
d_sub[['GRADE LEVEL', 'LEVEL']]

### The groupby function
It's easy to do an SQL-like group by operation with pandas. Let's say, if you want to
find the sum of the number of obese students in each of the grades, then you can use
the following command:

In [ ]:
df['NO. OBESE'].groupby(d['GRADE LEVEL']).sum()

This command chooses the number of obese students column, then uses the group
by method to group the data-based group level, and finally, the sum method sums
up the number. The same can be achieved by the following function too:

In [ ]:
d['NO. OBESE'].groupby(d['GRADE LEVEL']).aggregate(sum)

Here, the aggregate method is utilized. The sum function is passed to obtain the
required results.
It's also possible to obtain multiple kinds of aggregations on the same metric.
This can be achieved by the following command:

In [ ]:
df['NO. OBESE'].groupby(d['GRADE LEVEL']).aggregate([sum, mean,
std])

### Summary
In this chapter, we got familiarized with the NumPy and pandas packages. We
understood the different datatypes in pandas and how to utilize them. We learned
how to perform data cleansing and manipulation, in which we handled missing values
and performed string operations. This chapter gives us a foundation for data science
and you can dive deeper into NumPy and pandas by clicking on the following links:
* NumPy documentation: http://docs.scipy.org/doc/
* pandas documentation: http://pandas.pydata.org/
In the next chapter, we'll learn about the meaning of inferential statistics and what
they do, and also how to make sense of the different concepts in inferential statistics.